In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,"sudh",34.565,True]

In [5]:
a1 = np.array(l1)

In [6]:
a2 = np.array([[1,2,3],[4,5,6]])

In [7]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [8]:
a1.ndim

1

In [9]:
a2.ndim

2

In [10]:
a3.ndim

3

In [11]:
a1.size

7

In [12]:
a2.size

6

In [13]:
a3.size

9

In [14]:
#size represents a number of elements

In [15]:
a1.shape

(7,)

In [16]:
a2.shape

(2, 3)

In [17]:
a3.shape

(1, 3, 3)

In [18]:
# shape reprensents in the form of (z,y,x) : y - rows x-col

In [19]:
np.random.randint(2,5) #it reprenents number between 2 and 5

2

In [20]:
np.random.randint(2,5 , (3,4)) # it is going to generate 3 rows and 4 columns

array([[3, 3, 4, 4],
       [4, 2, 2, 3],
       [3, 3, 3, 2]])

In [21]:
np.random.randint(2,5 , (2,3,4))

array([[[3, 4, 4, 2],
        [4, 4, 2, 4],
        [2, 4, 2, 3]],

       [[4, 3, 3, 3],
        [3, 2, 4, 3],
        [2, 4, 3, 4]]])

In [22]:
np.random.rand(2,3)

array([[0.55213753, 0.87227927, 0.86894589],
       [0.93041382, 0.50454875, 0.92988553]])

In [23]:
a4 = np.random.randn(4,4)

In [24]:
# difference between rand and randn
if we have to generate normal distribution data then use randn
normally distributed means  : mean ->0 and normal distribution = 1

SyntaxError: invalid syntax (181147749.py, line 2)

In [25]:
a4

array([[ 0.20898808, -1.18474702, -0.29056003, -1.20133465],
       [ 0.50773956,  0.13930448,  1.1621085 , -1.97418756],
       [-0.07223418,  1.75491242,  1.28383996, -0.21111114],
       [ 0.7156143 , -0.54623678, -1.25955654,  0.19963158]])

In [26]:
a4.reshape(8,2) # when you are trying to reshape the data then you have to use factorial of 4*4

array([[ 0.20898808, -1.18474702],
       [-0.29056003, -1.20133465],
       [ 0.50773956,  0.13930448],
       [ 1.1621085 , -1.97418756],
       [-0.07223418,  1.75491242],
       [ 1.28383996, -0.21111114],
       [ 0.7156143 , -0.54623678],
       [-1.25955654,  0.19963158]])

In [27]:
a4.reshape(2,8)

array([[ 0.20898808, -1.18474702, -0.29056003, -1.20133465,  0.50773956,
         0.13930448,  1.1621085 , -1.97418756],
       [-0.07223418,  1.75491242,  1.28383996, -0.21111114,  0.7156143 ,
        -0.54623678, -1.25955654,  0.19963158]])

In [28]:
a4.reshape(16,1)

array([[ 0.20898808],
       [-1.18474702],
       [-0.29056003],
       [-1.20133465],
       [ 0.50773956],
       [ 0.13930448],
       [ 1.1621085 ],
       [-1.97418756],
       [-0.07223418],
       [ 1.75491242],
       [ 1.28383996],
       [-0.21111114],
       [ 0.7156143 ],
       [-0.54623678],
       [-1.25955654],
       [ 0.19963158]])

In [29]:
a4.reshape(1,16)

array([[ 0.20898808, -1.18474702, -0.29056003, -1.20133465,  0.50773956,
         0.13930448,  1.1621085 , -1.97418756, -0.07223418,  1.75491242,
         1.28383996, -0.21111114,  0.7156143 , -0.54623678, -1.25955654,
         0.19963158]])

In [30]:
a4.reshape(2,-1) # numpy will automatically convert negative number to 8

array([[ 0.20898808, -1.18474702, -0.29056003, -1.20133465,  0.50773956,
         0.13930448,  1.1621085 , -1.97418756],
       [-0.07223418,  1.75491242,  1.28383996, -0.21111114,  0.7156143 ,
        -0.54623678, -1.25955654,  0.19963158]])

In [31]:
a4.reshape(2,2,2,2)

array([[[[ 0.20898808, -1.18474702],
         [-0.29056003, -1.20133465]],

        [[ 0.50773956,  0.13930448],
         [ 1.1621085 , -1.97418756]]],


       [[[-0.07223418,  1.75491242],
         [ 1.28383996, -0.21111114]],

        [[ 0.7156143 , -0.54623678],
         [-1.25955654,  0.19963158]]]])

In [32]:
a4.reshape(1,2,2,4)

array([[[[ 0.20898808, -1.18474702, -0.29056003, -1.20133465],
         [ 0.50773956,  0.13930448,  1.1621085 , -1.97418756]],

        [[-0.07223418,  1.75491242,  1.28383996, -0.21111114],
         [ 0.7156143 , -0.54623678, -1.25955654,  0.19963158]]]])

In [33]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [34]:
a1[0]

'4'

In [35]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [36]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [37]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [38]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [39]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
accessing [2, 3] from a2
          [5, 6]

SyntaxError: invalid syntax (3758225754.py, line 1)

In [41]:
a2[:,1:3]

array([[2, 3],
       [5, 6]])

In [42]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [43]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [44]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [45]:
a5 = np.random.randint(2,90,(6,5))

In [46]:
a5

array([[50, 36, 55, 42, 71],
       [30, 70, 69, 73, 87],
       [27,  5, 50, 34, 21],
       [61, 59, 54, 66, 75],
       [52,  8, 56, 69, 40],
       [51, 31, 40, 89, 34]])

In [47]:
a5[a5>40]

array([50, 55, 42, 71, 70, 69, 73, 87, 50, 61, 59, 54, 66, 75, 52, 56, 69,
       51, 89])

In [48]:
# I would like to change value 78

In [49]:
a5[0,1]

36

In [50]:
a5[0,1] = 100

In [51]:
##Matrix Multiplication

In [52]:
a5

array([[ 50, 100,  55,  42,  71],
       [ 30,  70,  69,  73,  87],
       [ 27,   5,  50,  34,  21],
       [ 61,  59,  54,  66,  75],
       [ 52,   8,  56,  69,  40],
       [ 51,  31,  40,  89,  34]])

In [53]:
a6  = np.random.randint(0,3, (3,3))

In [54]:
a7 = np.random.randint(0,3, (3,3))

In [55]:
a6

array([[1, 2, 1],
       [2, 0, 0],
       [0, 0, 0]])

In [56]:
a7

array([[0, 0, 0],
       [0, 0, 1],
       [2, 0, 1]])

In [57]:
a6*a7

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
a6@a7

array([[2, 0, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
a7+100

array([[100, 100, 100],
       [100, 100, 101],
       [102, 100, 101]])

In [60]:
a6*2

array([[2, 4, 2],
       [4, 0, 0],
       [0, 0, 0]])

In [61]:
a6/0

C:\Users\91942\AppData\Local\Temp\ipykernel_16500\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\91942\AppData\Local\Temp\ipykernel_16500\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [inf, nan, nan],
       [nan, nan, nan]])

In [62]:
a6**2

array([[1, 4, 1],
       [4, 0, 0],
       [0, 0, 0]], dtype=int32)

In [63]:
a8 = np.zeros((4,4))

In [64]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
a9 = np.ones((6,6))

In [66]:
a9 + np.array([1,2,3,4,5,6]) # this entire operation is called as broadcasting

array([[2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7.]])

In [67]:
a9

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [68]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [69]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [70]:
a6.T

array([[1, 2, 0],
       [2, 0, 0],
       [1, 0, 0]])

In [71]:
a6

array([[1, 2, 1],
       [2, 0, 0],
       [0, 0, 0]])

In [72]:
a5

array([[ 50, 100,  55,  42,  71],
       [ 30,  70,  69,  73,  87],
       [ 27,   5,  50,  34,  21],
       [ 61,  59,  54,  66,  75],
       [ 52,   8,  56,  69,  40],
       [ 51,  31,  40,  89,  34]])

In [73]:
np.sqrt(a5)

array([[ 7.07106781, 10.        ,  7.41619849,  6.4807407 ,  8.42614977],
       [ 5.47722558,  8.36660027,  8.30662386,  8.54400375,  9.32737905],
       [ 5.19615242,  2.23606798,  7.07106781,  5.83095189,  4.58257569],
       [ 7.81024968,  7.68114575,  7.34846923,  8.1240384 ,  8.66025404],
       [ 7.21110255,  2.82842712,  7.48331477,  8.30662386,  6.32455532],
       [ 7.14142843,  5.56776436,  6.32455532,  9.43398113,  5.83095189]])

In [74]:
np.exp(a5)

array([[5.18470553e+21, 2.68811714e+43, 7.69478527e+23, 1.73927494e+18,
        6.83767123e+30],
       [1.06864746e+13, 2.51543867e+30, 9.25378173e+29, 5.05239363e+31,
        6.07603023e+37],
       [5.32048241e+11, 1.48413159e+02, 5.18470553e+21, 5.83461743e+14,
        1.31881573e+09],
       [3.10429794e+26, 4.20121040e+25, 2.83075330e+23, 4.60718663e+28,
        3.73324200e+32],
       [3.83100800e+22, 2.98095799e+03, 2.09165950e+24, 9.25378173e+29,
        2.35385267e+17],
       [1.40934908e+22, 2.90488497e+13, 2.35385267e+17, 4.48961282e+38,
        5.83461743e+14]])

In [75]:
np.log2(a5)

array([[5.64385619, 6.64385619, 5.78135971, 5.39231742, 6.14974712],
       [4.9068906 , 6.12928302, 6.10852446, 6.18982456, 6.4429435 ],
       [4.7548875 , 2.32192809, 5.64385619, 5.08746284, 4.39231742],
       [5.93073734, 5.88264305, 5.7548875 , 6.04439412, 6.22881869],
       [5.70043972, 3.        , 5.80735492, 6.10852446, 5.32192809],
       [5.67242534, 4.95419631, 5.32192809, 6.47573343, 5.08746284]])

In [76]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [77]:
np.arange(1.8 , 10.7 , 2.5)

array([1.8, 4.3, 6.8, 9.3])

In [78]:
np.linspace(2,3,num = 50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [79]:
np.linspace(2,3,num = 50 , retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [80]:
np.logspace(2,4,num = 4 , base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [81]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
Data Visulization

SyntaxError: invalid syntax (3559950323.py, line 1)

In [99]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns
from plotly.offline import iplot

In [100]:
cf.go_offline()

In [101]:
np.random.randn(100,3)

array([[ 0.02380496, -0.87229556, -0.59324733],
       [ 1.10546557,  1.22745915, -0.16127195],
       [-0.97917316, -0.34121234, -1.61583106],
       [ 1.94129961, -0.54501896,  0.33603946],
       [ 0.28697214, -0.11302449, -0.45663125],
       [ 0.3090794 ,  1.12403228,  0.58566018],
       [ 1.62424167, -0.23724445,  1.42232178],
       [ 0.30563403, -0.07154964,  1.30366855],
       [ 0.25712261, -0.69523831,  0.14814562],
       [-0.39657532,  0.00472667, -0.76725805],
       [ 0.11239832,  0.7375737 , -0.29900042],
       [-0.26602688,  0.36251331, -0.20252404],
       [ 1.06077157, -0.87381893,  0.52733431],
       [-0.44132562, -0.38304839, -0.31433694],
       [-0.10359428, -0.22500538, -1.83796782],
       [ 0.70242958,  2.08745931, -0.02264177],
       [-1.34702623, -0.1956335 ,  2.48933775],
       [ 1.5792578 , -0.37756227, -2.25509617],
       [ 0.06909414,  1.19448693, -0.51590741],
       [-0.02315779, -1.31037085,  0.46222293],
       [-0.23844461,  1.11546337,  0.577

In [102]:
df = pd.DataFrame(np.random.randn(100,3), columns = ['A' , 'B' , 'C'])

In [103]:
df

A         B         C
0   0.244689 -0.097571 -1.452456
1  -2.372388  1.105159 -0.589067
2   0.293194 -0.049464 -0.440838
3  -1.172390 -0.773559 -0.044033
4  -0.591603 -0.517642 -0.922599
..       ...       ...       ...
95  2.038672 -0.931716 -1.911761
96  0.949739 -0.425574 -0.459338
97 -0.865702  1.466687 -0.436766
98 -1.722676  0.755580 -1.363917
99 -0.856509 -1.520654 -0.045796

[100 rows x 3 columns]

In [104]:
df.iplot() 

In [112]:
df1 = pd.DataFrame(np.random.randint(3,100 , (100,1)))

In [113]:
df1

0
0   58
1   54
2   61
3   52
4   42
..  ..
95  36
96  94
97  25
98  96
99  97

[100 rows x 1 columns]

In [114]:
df1.iplot()

In [116]:
df.iplot(x = 'A' , y = 'B' , mode = 'markers')

In [105]:
df2 = sns.load_dataset('titanic')

In [106]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [107]:
df2.iplot(x = 'age' , y = 'fare' , mode = 'markers')

In [108]:
df2.iplot(x = 'age' , y = 'pclass' , mode = 'markers')

In [109]:
df2.iplot(x = 'fare' , y = 'pclass' , mode = 'markers')

In [110]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [111]:
df2.iplot(kind = 'bar' , x = 'sex' , y = 'survived')